stages:
  - lint

flake8_lint:
  stage: lint
  image: python:3.10
  script:
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming black
    - flake8 --config=.flake8
    - black --check .
  only:
    - merge_requests
    - main
  allow_failure: false