stages:
  - lint
  - test

flake8_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --config=.flake8
  only:
    - merge_requests
    - main

black_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check . --config=pyproject.toml
  only:
    - merge_requests
    - main
  allow_failure: false

django_tests:
  stage: test  
  image: python:3.10 
  variables:
    DJANGO_SETTINGS_MODULE: lyceum.settings 
    PYTHONUNBUFFERED: 1
  before_script:
    - pip install -r requirements/dev.txt 
  script:
    - cd lyceum
    - python3 manage.py test
  only:
    - merge_requests
    - main