stages:
  - lint

flake8_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --config=.flake8
  only:
    - merge_requests
    - main

black_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .
  only:
    - merge_requests
    - main
  allow_failure: false