stages:
  - prepare
  - lint
  - test

prepare_repo:
  stage: prepare
  script:
    - echo "Cleaning up leftover lock files"
    - rm -f /builds/django/2024/autumn/course/students/286724-betttttt-course-1187/.git/shallow.lock
    - echo "Cleanup complete"
  only:
    - merge_requests
    - main

flake8_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --config=.flake8
  only:
    - merge_requests
    - main

black_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check . --config=pyproject.toml
  only:
    - merge_requests
    - main
  allow_failure: false

django_tests:
  stage: test  
  image: python:3.10 
  variables:
    DJANGO_SETTINGS_MODULE: lyceum.settings 
    PYTHONUNBUFFERED: 1
  before_script:
    - pip install -r requirements/dev.txt
    - pip install -r requirements/test.txt
  script:
    - cd lyceum
    - python3 manage.py test
  only:
    - merge_requests
    - main
  needs:
    - prepare_repo