stages:
  - lint

flake8_lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --exclude=venv,.gitignore,README.md .
  only:
    - merge_requests
    - main