# Generated by Django 4.2.14 on 2024-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Отзыв"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Почта"),
                ),
            ],
        ),
    ]
