# Generated by Django 4.2.14 on 2024-11-17 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackformmodel",
            name="created_on",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="время создания",
            ),
            preserve_default=False,
        ),
    ]
