# Generated by Django 4.2.14 on 2024-11-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedbackformmodel_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Отзыв"),
                ),
                (
                    "created_on",
                    models.DateField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackAuther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Почта"),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FeedbackFormModel",
        ),
    ]
