# Generated by Django 4.2.14 on 2024-11-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedback_feedbackauther_delete_feedbackformmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedbackauther",
            old_name="email",
            new_name="mail",
        ),
    ]
