# Generated by Django 4.2.14 on 2024-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_rename_email_feedbackauther_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackauther",
            name="mail",
            field=models.EmailField(max_length=200, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="feedbackauther",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
    ]
