# Generated by Django 4.2.14 on 2024-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_feedbackauther_mail_alter_feedbackauther_name",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="created_on",
            new_name="created",
        ),
    ]
