# Generated by Django 4.2.14 on 2024-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_rename_created_on_feedback_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.CharField(max_length=250, verbose_name="Отзыв"),
        ),
    ]
