# Generated by Django 4.2.14 on 2024-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedback_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackauther",
            name="mail",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
