# Generated by Django 4.2.14 on 2024-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_alter_feedbackauther_mail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="created",
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="время создания"
            ),
            preserve_default=False,
        ),
    ]
