# Generated by Django 4.2.14 on 2024-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_alter_feedbackauther_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="mail",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Имя"
            ),
        ),
    ]
