# Generated by Django 4.2.14 on 2024-11-22 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_profile_mail_alter_profile_user"),
        ("users", "0003_profile_is_active_alter_profile_mail"),
        ("users", "0004_alter_profile_birthday_alter_profile_image"),
        ("users", "0005_remove_profile_is_active_alter_profile_birthday"),
        ("users", "0006_rename_coffe_count_profile_coffee_count"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        default="2000-01-01", verbose_name="дата рождения"
                    ),
                ),
                (
                    "coffee_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="чашки кофе"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="profile/images/picture.png",
                        upload_to=users.models.Profile.image_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="почта"),
                ),
            ],
        ),
    ]
