# Generated by Django 4.2.14 on 2024-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_mail_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mail",
            field=models.EmailField(max_length=254, verbose_name="почта"),
        ),
    ]
