# Generated by Django 4.2.14 on 2024-11-22 08:17

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_is_active_alter_profile_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                default="2000-01-01", verbose_name="дата рождения"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/images/picture.png",
                upload_to=users.models.Profile.image_path,
                verbose_name="изображение",
            ),
            preserve_default=False,
        ),
    ]
