# Generated by Django 4.2.14 on 2024-11-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_birthday_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                default="2000-01-01", verbose_name="дата рождения"
            ),
        ),
    ]
