# Generated by Django 4.2.14 on 2024-11-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_is_active_alter_profile_birthday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="coffe_count",
            new_name="coffee_count",
        ),
    ]
