# Generated by Django 4.2.14 on 2024-11-22 20:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0001_initial_squashed_0006_rename_coffe_count_profile_coffee_count",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                upload_to=users.models.Profile.image_path,
                verbose_name="изображение",
            ),
        ),
    ]
