# Generated by Django 4.2.14 on 2024-10-18 20:03

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        (
            "catalog",
            "0001_initial_squashed_0002_alter_category_name_alter_category_slug_and_more",
        ),
        ("catalog", "0003_alter_category_options_alter_item_options_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите короткое название, не более 50 символов.",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Слаг может содержать тольколатинские буквы, цифры, дефисы и подчёркивания.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                        verbose_name="слаг",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        help_text="Введите целое число от 0 до 32767",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name="вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите короткое название, не более 50 символов.",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Слаг может содержать тольколатинские буквы, цифры, дефисы и подчёркивания.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите короткое название, не более 50 символов.",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите полное описание товара.",
                        validators=[catalog.models.validate_text],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
