# Generated by Django 4.2.14 on 2024-10-17 14:09

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Слаг может содержать только латинские буквы, цифры, дефисы и подчёркивания.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Вес"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[catalog.models.validate_text],
                        verbose_name="Текст",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CatalogTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Слаг может содержать только латинские буквы, цифры, дефисы и подчёркивания.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                        verbose_name="Слаг",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
