# Generated by Django 4.2.14 on 2024-10-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_catalogcategory_catalogitem_catalogtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.catalogcategory",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="tags",
            field=models.ManyToManyField(
                related_name="items",
                to="catalog.catalogtag",
                verbose_name="Теги",
            ),
        ),
    ]
