# Generated by Django 4.2.14 on 2024-11-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_squashed_0003_remove_item_on_main"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainimage",
            name="item",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="MainImage",
        ),
    ]
