# Generated by Django 4.2.14 on 2024-10-17 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_catalogcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcategory",
            name="slug",
            field=models.SlugField(
                help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Слаг может содержать тольколатинские буквы, цифры, дефисы и подчёркивания.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="slug",
            field=models.SlugField(
                help_text="Только цифры, латинские буквы, символы '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Слаг может содержать тольколатинские буквы, цифры, дефисы и подчёркивания.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
                verbose_name="Слаг",
            ),
        ),
    ]
