# Generated by Django 4.2.14 on 2024-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_item_on_main"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="on_main",
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=False),
        ),
    ]
